config/routes.rb
SmRc198::Application.routes.draw do

#Railscast 203 started
#    can use get alone or put ,  match will be for collection of http verbs
    #match "post" => "posts#index" ,  via: [:get, :post]
    #without format it vl give error eg localhost:3000/post.pdf
    #  match "post.format" => "posts#index" ,  via: [:get, :post]
    #format will be optional
      match "/post(.:format)" => "posts#index" ,  via: [:get, :post], as: :sample   #now u can refer as redirect_to sample_url or sample_path (as: functionality)
      #  : is used for dynamic value and () is used for optional and can be nested
      #match ":year(/:month(/:day))" => "posts#about" ,  via: [:get, :post]
      #As above route is very generic it will accept 1998 or sweety as year , but make it acceptable for 19998 use
      match ":year(/:month(/:day))" => "posts#about" ,  via: [:get, :post] , constraints: {year: /\d{4}/, month: /\d{2}/, day: /\d{2}/ }
      #constarint specfic to user agent
      #match "secret" => "posts#secret", constraints: { host: /localhost/ } ,  via: [:get, :post]
      #If dont wat to create controller action and temlate use rack
       match "/hello" => proc { |env| [200, {}, ["Welcome"]] }, via: [:get,:post]
#end of 203
#  get "profile/:id", to: "posts#profile"
  resources :posts do
    #use on: if having single custom action
    get 'edit_multiple', on: :collection
    collection do
      put 'update_multiple'
      put 'update_individual'
      get 'edit_individual'
    end
    #get 'comment'  , on: :member                        #Railscast 204

  end
  #For collection custom action
  #get '/edit_multiple', to: 'posts#edit_multiple'
  get '/comment/:id', to: 'posts#comment', as: 'comment'


  root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  validates_uniqueness_of :name
  validates_uniqueness_of :content
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :name
  has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :comment]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  def edit_multiple
    @posts = Post.find(params[:post_ids])
  end

  def update_multiple
    @posts  = Post.find(params[:post_ids])
    @posts.each do |post|
      post.update_attributes(post_params.reject {|v| v.blank?})
    end
    respond_to do |format|
      format.html { redirect_to posts_path, notice: 'Updated' }
    end
  end

  def edit_individual
    @posts = Post.find(params[:post_ids])
  end

  def update_individual
    #update all posts with single line
    @posts = Post.update(params[:posts].keys, params[:posts].values).reject {|p| p.errors.empty?}
    if @posts.empty?
      flash[:notice] = "Posts updated"
      redirect_to posts_path
    else
      render 'edit_individual'
    end
  end
  #sample action to learn routes
  def about

  end

  #Railscast 204
  def comment
    @comments = @post.comments.all
    unless params[:"/comment/#{params[:id]}"].blank?
      @name = params[:"/comment/#{params[:id]}"][:name]
      @content = params[:"/comment/#{params[:id]}"][:content]
      @post.comments.create(name: @name, content: @content)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= simple_form_for @comment, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :content %>
  <%= f.input :post_id %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                comments_path, :class => 'btn' %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<%- model_class = Comment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/comments/index.html.erb
<%- model_class = Comment -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:content) %></th>
      <th><%= model_class.human_attribute_name(:post_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= link_to comment.id, comment_path(comment) %></td>
        <td><%= comment.name %></td>
        <td><%= comment.content %></td>
        <td><%= comment.post_id %></td>
        <td><%=l comment.created_at %></td>
        <td>
          <%= link_to 'comments', comment_posts_path, :class => 'btn btn-mini' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_comment_path(comment), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      comment_path(comment),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_comment_path,
            :class => 'btn btn-primary' %>

app/views/comments/new.html.erb
<%- model_class = Comment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/comments/show.html.erb
<%- model_class = Comment -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @comment.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:content) %>:</strong></dt>
  <dd><%= @comment.content %></dd>
  <dt><strong><%= model_class.human_attribute_name(:post_id) %>:</strong></dt>
  <dd><%= @comment.post_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              comments_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_comment_path(@comment), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              comment_path(@comment),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title>SmRc198</title>
      <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
      <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
      <%= csrf_meta_tags %>
    </head>
    <body>
        <div class="span4"></div>
        <div class="span4">
            <% flash.each do |name,msg| %>
                <div class="alert alert-<%= name == :notice ? 'success' : 'error' %>" >
                  <a class="close" data-dismiss="alert">x</a>
                  <%= msg %>
                </div>
            <% end %>
            <%= yield %>
        </div>

        <div class="span4"></div>
    </body>
</html>

app/views/posts/_fields.html.erb
<% if params[:fields].blank? || params[:fields] == "name" %>
<%= f.input :name %>
<% end %>

app/views/posts/_form.html.erb
<%= simple_form_for @post, :html => { :class => 'form-horizontal' } do |f| %>
  <%= render 'fields' , f: f %>
    <div class="form-actions">
      <%= f.button :submit, :class => 'btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  posts_path, :class => 'btn' %>
    </div>
<% end %>

app/views/posts/about.html.erb
<h3>Year Month Days</h3>

<%= debug params %>

app/views/posts/comment.html.erb
<% unless @comments.nil? %>
    <h3>All Comments</h3>
    <table border="1px solid blue" class="striped">
        <% @comments.each do |comment| %>
           <tr>
           <td><%= comment.name.html_safe %><br/></td>
           <td><%=raw comment.content %></td>
           </tr>
        <% end %>
    </table>
<% end %>

<h3>Create Comments</h3>
<%= form_for comment_path, method: :get do |f| %>
    <%= f.label 'name' %>
    <%= f.text_field :name %>

    <%= f.label 'Content' %>
    <%= f.text_field :content %>

    <%= f.submit 'create comment' , :class => 'btn btn-mini' %>
<% end %>

app/views/posts/edit.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/edit_individual.html.erb
<%- model_class = Post -%>
<h3>Edit Posts</h3>
<!--As form_for work on single object so form_tag is used-->
<%= simple_form_for :post, :url => update_individual_posts_path, method: :put do |d| %>
    <% @posts.each do |post| %>
        <!--form builder-->
       <%= simple_fields_for "posts[]" , post do |f| %>
            <h5><%= post.name %></h5>
            <%= render 'fields' , f: f %>
       <% end %>
    <% end %>
    <%= d.submit 'Update posts' %>
<% end %>

app/views/posts/edit_multiple.html.erb
<h3>Edit Multiple Posts</h3>
<%= simple_form_for :post, :url => update_multiple_posts_path, :method => :put do |f| %>
    <ul>
      <% for post in @posts %>
          <li>
            <%#= f.hidden_field "post_ids[]" , :value =>  %>
            <%= hidden_field_tag "post_ids[]", post.id %>
            <%=  post.name %>
          </li>
      <% end %>
    </ul>

    <div class="field">
      <%= f.input :name %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/posts/index.html.erb
<%- model_class = Post -%>
<%#= form_tag edit_multiple_posts_path, :method => :get do %>
<%= form_tag edit_individual_posts_path, :method => :get do %>
      <div class="page-header">
      <h3><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h3>
    </div>
    <table class="table table-striped">
      <thead>
        <tr>
          <th><%= model_class.human_attribute_name(:name) %></th>
        </tr>
      </thead>
      <tbody>
        <% @posts.each do |post| %>
          <tr>
            <td><%= check_box_tag "post_ids[]" , post.id %></td>
            <td><%= post.name %></td>
            <td>
              <%= link_to 'comments', comment_path(post), :class => 'btn btn-mini' %>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_post_path(post), :class => 'btn btn-mini' %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                          post_path(post),
                          :method => :delete,
                          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                          :class => 'btn btn-mini btn-danger' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= select_tag :field, options_for_select([["All Fields", ""], ["name", "name"]]) , prompt: "Please Select" %>
    <%= submit_tag "Edit Checked" , class: 'btn btn-primary'%>
<% end %>
    <%= link_to t('.new', :default => t("helpers.links.new")),
                new_post_path,
                :class => 'btn btn-primary' %>

app/views/posts/new.html.erb
<div class="span4"></div>
<div class="span6">
    <%- model_class = Post -%>
    <div class="page-header">
      <h3><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h3>
    </div>
    <%= render :partial => 'form' %>
</div>
<div class="span2"></div>

app/views/posts/show.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @post.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              posts_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_post_path(@post), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              post_path(@post),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>